# Generated by Django 2.2.4 on 2019-08-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='Game',
        ),
    ]
